name: Release Windows bundle

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install build tools
      run: pip install meson ninja

    - name: Checkout Gtk
      run: |
        BRANCH=`cat ./BRANCH`
        git clone --branch $BRANCH --depth 1 https://gitlab.gnome.org/GNOME/gtk.git
      shell: bash

    - name: Setup build
      run: |
        export INSTALL_PATH=`pwd`/gtk4
        cd gtk
        meson setup build \
          --prefix=$INSTALL_PATH \
          --libdir=lib \
          --wrap-mode=forcefallback \
          -Dbuildtype=release \
          -Dcpp_std=c++11 \
          -Dglib:tests=false \
          -Dpixman:tests=disabled \
          -Dbuild-tests=false \
          -Ddemos=false \
          -Dwin32-backend=true \
          -Dx11-backend=false \
          -Dmedia-gstreamer=disabled
      shell: bash

    - name: Print options
      run: meson configure gtk\build

    - run: meson introspect --dependencies gtk\build

    - run: meson compile -C gtk\build

    - run: meson install -C gtk\build

    - name: Archive
      id: archive
      run: |
        BRANCH=`cat ./BRANCH`
        tar -czvf gtk4-win32-$BRANCH.tar.gz ./gtk4
      shell: bash

    - uses: softprops/action-gh-release@v1
      with:
        files: gtk4-win32-*.tar.gz
