name: Release macos bundle

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: checkout
      run: |
        BRANCH=`cat ./BRANCH`
        git clone --branch $BRANCH --depth 1 https://gitlab.gnome.org/GNOME/gtk.git

    - name: install meson
      run: brew install llvm meson ninja

    - name: setup
      run: |
        export INSTALL_PATH=`pwd`/gtk4
        cd gtk
        meson setup build --prefix=$INSTALL_PATH --libdir=lib -Dcpp_std=c++11 -Dbuild-tests=false -Dmacos-backend=true -Dx11-backend=false -Dmedia-gstreamer=disabled

    - run: meson introspect --dependencies gtk/build
    - run: meson compile -C gtk/build
    - run: meson install -C gtk/build

    - name: archive
      run: |
        tar -czvf gtk4.tar.gz ./gtk4

    - uses: softprops/action-gh-release@v1
      with:
        files: gtk4.tar.gz
